# Generated by Django 4.2 on 2024-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Clothing', 'Clothing'), ('Home & Garden', 'Home & Garden'), ('Books', 'Books'), ('Toys', 'Toys'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Health & Household', 'Health & Household'), ('Jewelry', 'Jewelry'), ('Pet Supplies', 'Pet Supplies'), ('Music', 'Music'), ('Movies & TV', 'Movies & TV'), ('Grocery', 'Grocery'), ('Software', 'Software'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Baby Products', 'Baby Products'), ('Industrial & Scientific', 'Industrial & Scientific'), ('luggage & Travel Gear', 'luggage & Travel Gear'), ('Arts, Crafts & Sewing', 'Arts, Crafts & Sewing'), ('Other', 'Other')], max_length=50),
        ),
    ]
